site_name: Pylnlib
site_description: Documentation for the pylnlib library.
site_url: https://varkenvarken.github.io/pylnlib/
site_dir: docs
repo_url: https://github.com/varkenvarken/pylnlib
repo_name: pylnlib

docs_dir: documentation

theme:
    name: 'material'
    palette:
      primary: purple
    font:
      text: 'Gentium Basic'
    logo: assets/logo.svg
    favicon: assets/favicon.png

nav:
  - Home: 'README.md'
  - Pylnlib: 'API/pylnlib.md'

markdown_extensions:
  - admonition
  - codehilite
  - jetblack_markdown.autodoc:
      class_from_init: true
      ignore_dunder: true
      ignore_private: true
      ignore_all: false
      prefer_docstring: true
      template_folder: null

extra_css:
  - stylesheets/extra.css
