name: Mkdocs 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - run: pip install 
      - run: echo `pwd`
      - run: PYTHONPATH=`pwd` mkdocs -v build
      - run: PYTHONPATH=`pwd` mkdocs gh-deploy --force
